### ISSUE TITLE
bs3-call_methylation gave no results

### ISSUE THREAD

**Issue by k1197445** [khuang28jhu/bs3#20]
I used bs3-call_methylation with alignment from test data, but got error message as follow,

     BS-Seeker3 beta

[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::bgzf_flush] File write failed (wrong size)
samtools view: writing to standard output failed: Broken pipe
[E::bgzf_close] File write failed
samtools view: error closing standard output: -1
[2019-01-31 16:53:54] indexing sorted alignments
[E::hts_open_format] Failed to open file output.bam
samtools index: failed to open "output.bam": No such file or directory
[2019-01-31 16:53:54] calculating methylation levels
[E::hts_open_format] Failed to open file output.bam
Traceback (most recent call last):
  File "bs3-call_methylation.py", line 128, in <module>
    sorted_input = pysam.Samfile('output.bam', 'rb')
  File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 935, in pysam.libcalignmentfile.AlignmentFile._open
IOError: [Errno 2] could not open alignment file `output.bam`: No such file or directory

**Comment by anapopicsbg** [comment]
Has anybody solved this issue? Thank you!

**Comment by Bio-finder** [comment]
Hi,
I get also the same issue so I think that it's quite important to try to solve this. Does someone has any clues of what is happening?
