### ISSUE TITLE
Error index

### ISSUE THREAD

**Issue by lab23UGD** [khuang28jhu/bs3#37]
When I tried to index the genome reference the following error appears:

Traceback (most recent call last):
  File "bs3-build.py", line 5, in <module>
    from bs_index.wg_build import *
  File "bs_seeker3/bs_index/wg_build.py", line 49
    chrom_num += 1
                 ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by lab23UGD** [comment]
There are many code errors so I can't run this program. For example: 

Traceback (most recent call last):
  File "bs3-build.py", line 5, in <module>
    from bs_index.wg_build import *
  File "bs_seeker3/bs_index/wg_build.py", line 1, in <module>
    from bs_utils.utils import *
  File "bs_seeker3/bs_utils/utils.py", line 25
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?

**Comment by Leo-ccc** [comment]
BS3 is baed on python2, not python3.
